; Copie ce fichier en platformio.override.ini pour tes réglages locaux.
; Ce fichier d'override est chargé automatiquement par PlatformIO
; et ignoré par Git.

[env:soundpanel7_usb]
upload_port = /dev/cu.usbmodemXXXX
monitor_port = /dev/cu.usbmodemXXXX

[env:soundpanel7_ota]
upload_port = 192.168.1.137
; Exemple si besoin:
; upload_flags =
;   --port=3232
;   --auth=SoundPanel7
;   --host_ip=192.168.1.42

[env:soundpanel7b_usb]
upload_port = /dev/cu.usbmodemXXXX
monitor_port = /dev/cu.usbmodemXXXX

[env:soundpanel7b_ota]
upload_port = 192.168.1.138

[env:soundpanel7_headless_usb]
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

[env:soundpanel7_headless_ota]
upload_port = 192.168.1.137
