;
; ============================================================
; SoundPanel 7 — Waveshare ESP32-S3-Touch-LCD-7
; Arduino + PlatformIO
; ============================================================

[platformio]
default_envs = soundpanel7_usb

[env]
framework = arduino

platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
platform_packages =
  platformio/framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#3.1.1
  platformio/framework-arduinoespressif32-libs@https://dl.espressif.com/AE/esp-arduino-libs/esp32-3.1.1-h.zip

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

; Filesystem for web UI
board_build.filesystem = littlefs

lib_deps =
  https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
  https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
  https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
  https://github.com/lvgl/lvgl.git#v8.4.0
  knolleary/PubSubClient@^2.8
  tzapu/WiFiManager@^2.0.17
  esp32async/ESPAsyncWebServer@^3.0.0
  esp32async/AsyncTCP@^3.3.8

[common]
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_LVGL_H_INCLUDE_SIMPLE
  -I src
  -I include
  -DARDUINO_USB_CDC_ON_BOOT=0

  ; mock audio par défaut
  -DSOUNDPANEL7_MOCK_AUDIO=1

[rgb_mipi_lcd]
build_flags =
  -DLV_COLOR_16_SWAP=0

[env:soundpanel7_usb]
board = esp32-s3-devkitc-1

board_upload.flash_size = 16MB

; IMPORTANT : table OTA-compatible pour que l'OTA fonctionne ensuite
board_build.partitions = default_16MB.csv

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

upload_port = /dev/cu.usbmodem5AE71120401
monitor_port = /dev/cu.usbmodem5AE71120401
upload_speed = 115200

upload_flags =
  --before
  no_reset_no_sync
  --after
  hard_reset
  --connect-attempts
  10

build_flags =
  ${common.build_flags}
  ${rgb_mipi_lcd.build_flags}
  -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
  -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7
  -DBOARD_HAS_PSRAM

[env:soundpanel7_ota]
board = esp32-s3-devkitc-1

board_upload.flash_size = 16MB

; même table de partitions que l'env USB
board_build.partitions = default_16MB.csv

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

upload_protocol = espota
upload_port = 192.168.1.137
monitor_port = /dev/cu.usbmodem5AE71120401

; port OTA ArduinoOTA par défaut = 3232
upload_flags =
  --port=3232
  --auth=SoundPanel7

build_flags =
  ${common.build_flags}
  ${rgb_mipi_lcd.build_flags}
  -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
  -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7
  -DBOARD_HAS_PSRAM