\
#pragma once
#include <stdint.h>

#define SOUNDPANEL7_VERSION "0.2.17"
#define SOUNDPANEL7_BUILD_DATE __DATE__ " " __TIME__

#ifndef SOUNDPANEL7_BUILD_ENV
#define SOUNDPANEL7_BUILD_ENV "unknown"
#endif

#ifndef SOUNDPANEL7_RELEASE_MANIFEST_URL
#define SOUNDPANEL7_RELEASE_MANIFEST_URL "https://github.com/jjtronics/SoundPanel7/releases/latest/download/release-manifest.json"
#endif

#ifndef SOUNDPANEL7_RELEASE_LATEST_API_URL
#define SOUNDPANEL7_RELEASE_LATEST_API_URL "https://api.github.com/repos/jjtronics/SoundPanel7/releases/latest"
#endif

// Compile-time default (can be overridden by build_flags)
#ifndef SOUNDPANEL7_MOCK_AUDIO
#define SOUNDPANEL7_MOCK_AUDIO 1
#endif

#ifndef SOUNDPANEL7_HAS_SCREEN
#if defined(BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7)
#define SOUNDPANEL7_HAS_SCREEN 1
#else
#define SOUNDPANEL7_HAS_SCREEN 0
#endif
#endif

#define SOUNDPANEL7_AUDIO_BOARD_PROFILE_WAVESHARE_7 1
#define SOUNDPANEL7_AUDIO_BOARD_PROFILE_HEADLESS_S3 2

#ifndef SOUNDPANEL7_AUDIO_BOARD_PROFILE
#if defined(BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7)
#define SOUNDPANEL7_AUDIO_BOARD_PROFILE SOUNDPANEL7_AUDIO_BOARD_PROFILE_WAVESHARE_7
#else
#define SOUNDPANEL7_AUDIO_BOARD_PROFILE SOUNDPANEL7_AUDIO_BOARD_PROFILE_HEADLESS_S3
#endif
#endif

#ifndef SOUNDPANEL7_TARDIS_SUPPORTED
#if SOUNDPANEL7_HAS_SCREEN
#define SOUNDPANEL7_TARDIS_SUPPORTED 0
#else
#define SOUNDPANEL7_TARDIS_SUPPORTED 1
#endif
#endif

#ifndef SOUNDPANEL7_TARDIS_INTERIOR_LED_PIN
#define SOUNDPANEL7_TARDIS_INTERIOR_LED_PIN 15
#endif

#ifndef SOUNDPANEL7_TARDIS_EXTERIOR_LED_PIN
#define SOUNDPANEL7_TARDIS_EXTERIOR_LED_PIN 16
#endif

#ifndef SOUNDPANEL7_TARDIS_LED_ACTIVE_HIGH
#define SOUNDPANEL7_TARDIS_LED_ACTIVE_HIGH 1
#endif

#ifndef SOUNDPANEL7_TARDIS_INTERIOR_RGB_SUPPORTED
#if SOUNDPANEL7_TARDIS_SUPPORTED
#define SOUNDPANEL7_TARDIS_INTERIOR_RGB_SUPPORTED 1
#else
#define SOUNDPANEL7_TARDIS_INTERIOR_RGB_SUPPORTED 0
#endif
#endif

#ifndef SOUNDPANEL7_TARDIS_INTERIOR_RGB_PIN
#define SOUNDPANEL7_TARDIS_INTERIOR_RGB_PIN 48
#endif

#ifndef SOUNDPANEL7_TARDIS_INTERIOR_RGB_PIXEL_COUNT
#define SOUNDPANEL7_TARDIS_INTERIOR_RGB_PIXEL_COUNT 1
#endif

#ifndef SOUNDPANEL7_TARDIS_INTERIOR_RGB_BRIGHTNESS
#define SOUNDPANEL7_TARDIS_INTERIOR_RGB_BRIGHTNESS 96
#endif

#if SOUNDPANEL7_AUDIO_BOARD_PROFILE == SOUNDPANEL7_AUDIO_BOARD_PROFILE_WAVESHARE_7
#ifndef SOUNDPANEL7_DEFAULT_ANALOG_PIN
#define SOUNDPANEL7_DEFAULT_ANALOG_PIN 6
#endif
#ifndef SOUNDPANEL7_DEFAULT_PDM_CLK_PIN
#define SOUNDPANEL7_DEFAULT_PDM_CLK_PIN 12
#endif
#ifndef SOUNDPANEL7_DEFAULT_PDM_DATA_PIN
#define SOUNDPANEL7_DEFAULT_PDM_DATA_PIN 13
#endif
#ifndef SOUNDPANEL7_DEFAULT_INMP441_BCLK_PIN
#define SOUNDPANEL7_DEFAULT_INMP441_BCLK_PIN 12
#endif
#ifndef SOUNDPANEL7_DEFAULT_INMP441_WS_PIN
#define SOUNDPANEL7_DEFAULT_INMP441_WS_PIN 11
#endif
#ifndef SOUNDPANEL7_DEFAULT_INMP441_DATA_PIN
#define SOUNDPANEL7_DEFAULT_INMP441_DATA_PIN 13
#endif
#else
#ifndef SOUNDPANEL7_DEFAULT_ANALOG_PIN
#define SOUNDPANEL7_DEFAULT_ANALOG_PIN 4
#endif
#ifndef SOUNDPANEL7_DEFAULT_PDM_CLK_PIN
#define SOUNDPANEL7_DEFAULT_PDM_CLK_PIN 12
#endif
#ifndef SOUNDPANEL7_DEFAULT_PDM_DATA_PIN
#define SOUNDPANEL7_DEFAULT_PDM_DATA_PIN 13
#endif
#ifndef SOUNDPANEL7_DEFAULT_INMP441_BCLK_PIN
#define SOUNDPANEL7_DEFAULT_INMP441_BCLK_PIN 12
#endif
#ifndef SOUNDPANEL7_DEFAULT_INMP441_WS_PIN
#define SOUNDPANEL7_DEFAULT_INMP441_WS_PIN 11
#endif
#ifndef SOUNDPANEL7_DEFAULT_INMP441_DATA_PIN
#define SOUNDPANEL7_DEFAULT_INMP441_DATA_PIN 13
#endif
#endif
